# 端口号
server:
  port: 1122

# mysql数据库
spring:
  datasource:
    url: jdbc:mysql://47.103.72.163:3306/kttx-phoenix
    username: root
    password: '@Kttx20190515'
    driver-class-name: com.mysql.jdbc.Driver

#mybatis配置
mybatis:
    config-locations : classpath:mybatis/mybatis-config.xml
    mapper-locations : classpath:mybatis/mapper/*/*.xml
    type-aliases-package : com.banyuan.pangu.tank.mapper